export const apiActionTypes = {
    GET_UNIVERSITIES_REQUEST: 'GET_UNIVERSITIES_REQUEST',
    GET_UNIVERSITIES_SUCCESS: 'GET_UNIVERSITIES_SUCCESS',
    GET_UNIVERSITIES_FAILURE: 'GET_UNIVERSITIES_FAILURE'
};